image: ubuntu:18.04

job:
  script:
    - apt-get update
    - apt-get install -y gcc g++ cmake libgtest-dev
    - cd /usr/src/gtest
    - cmake CMakeLists.txt && make
    - cp *.a /usr/lib
    - cd -
    - cmake CMakeLists.txt && make tests
    

