image: ubuntu:18.04

job:
  script:
    - apt-get update
    - apt-get install -y clang cmake libgtest-dev
    - cd /usr/src/gtest
    - cmake CMakeLists.txt && make
    - cp *.a /usr/lib
    - cd -
    - cd archiver && mkdir build && cd build && cmake .. && cd ../..
    - cd binary_trie && mkdir build && cd build && cmake .. && cd ../..
    - cd priority_queue && mkdir build && cd build && cmake .. && cd ../..
    - cd reader && mkdir build && cd build && cmake .. && cd ../..
    - cd writer && mkdir build && cd build && cmake .. && cd ../..
    - cd archiver/build && make tests  && cd ../..
    - cd binary_trie/build && make tests  && cd ../..
    - cd priority_queue/build && make tests  && cd ../..
    - cd reader/build && make tests  && cd ../..
    - cd writer/build && make tests  && cd ../..
    

