image: ubuntu:18.04

job:
  script:
    - apt update
    - apt install -y clang-11 cmake libgtest-dev
    - cd /usr/src/gtest
    - cmake CMakeLists.txt && make
    - cp *.a /usr/lib
    - cd -
    - cmake CMakeLists.txt && make tests
    

